eu_main_homepage:
    path:     /
    defaults: { _controller: EUMainBundle:Index:index }
eu_main_main_pot:
    path:     /participate-main-pot
    defaults: { _controller: EUMainBundle:Index:mainpot }
eu_main_rules:
    path:     /rules
    defaults: { _controller: EUMainBundle:Index:rules }
eu_main_tester:
    path:     /test
    defaults: { _controller: EUMainBundle:Index:test}

bets_list:
    path: /bets
    defaults: { _controller: EUMainBundle:Bet:list}
    methods: [GET]
bets_create:
    path:   /bets
    defaults: { _controller: EUMainBundle:Bet:create }
    methods: [POST]
bets_read:
    path:   /bets/{id}
    defaults: { _controller: EUMainBundle:Bet:read }
    methods: [GET]
    requirements:
        id: "\d+"
bets_update:
    path:   /bets/{id}
    defaults: { _controller: EUMainBundle:Bet:update }
    methods: [POST|PUT]
    requirements:
        id: "\d+"
bets_delete:
    path:   /bets/{id}
    defaults: { _controller: EUMainBundle:Bet:delete }
    methods: [DELETE]
    requirements:
        id: "\d+"

games_list:
    path: /games
    defaults: { _controller: EUMainBundle:Game:list }
    methods: [GET]
games_read:
    path: /games/{id}
    defaults: { _controller: EUMainBundle:Game:read }
    methods: [GET]
    requirements:
        id: "\d+"
games_bets_list:
    path: /games/{id}/bets
    defaults: { _controller: EUMainBundle:Game:listBets }
    methods: [GET]
    requirements:
        id: "\d+"

pots_list:
    path: /pots
    defaults: { _controller: EUMainBundle:Pot:list }
    methods: [GET]
pots_create:
    path:   /pots
    defaults: { _controller: EUMainBundle:Pot:create }
    methods: [POST]
pots_read:
    path: /pots/{id}
    defaults: { _controller: EUMainBundle:Pot:read }
    methods: [GET]
    requirements:
        id: "\d+"
pots_update:
    path: /pots/{id}
    defaults: { _controller: EUMainBundle:Pot:update }
    methods: [POST|PUT]
    requirements:
        id: "\d+"
pots_delete:
    path: /pots/{id}
    defaults: { _controller: EUMainBundle:Pot:delete }
    methods: [DELETE]
    requirements:
        id: "\d+"
pots_invite:
    path: /pots/{id}/invite/{iduser}
    defaults: { _controller: EUMainBundle:Pot:invite }
    methods: [GET]
    requirements:
        id: "\d+"
        iduser: "\d+"
pots_users_list:
    path: /pots/{id}/users
    defaults: { _controller: EUMainBundle:Pot:listUsers }
    methods: [GET]
    requirements:
        id: "\d+"
pots_bets_list:
    path: /pots/{id}/bets
    defaults: { _controller: EUMainBundle:Pot:listBets }
    methods: [GET]
    requirements:
        id: "\d+"
pots_participations_list:
    path: /pots/{id}/participations
    defaults: { _controller: EUMainBundle:Pot:listParticipations }
    methods: [GET]
    requirements:
        id: "\d+"

participations_list:
    path: /participations
    defaults: { _controller: EUMainBundle:Participation:list }
    methods: [GET]
participations_accept:
    path: /participations/{id}/accept
    defaults: { _controller: EUMainBundle:Participation:accept }
    methods: [GET]
    requirements:
        id: "\d+"
participations_pay:
    path: /participations/{id}/paid
    defaults: { _controller: EUMainBundle:Participation:paid }
    methods: [GET]
    requirements:
        id: "\d+"
participations_delete:
    path: /participations/{id}
    defaults: { _controller: EUMainBundle:Participation:delete }
    methods: [DELETE]
    requirements:
        id: "\d+"

teams_list:
    path: /teams
    defaults: { _controller: EUMainBundle:Team:list }
    methods: [GET]
teams_read:
    path: /teams/{id}
    defaults: { _controller: EUMainBundle:Team:read }
    methods: [GET]
    requirements:
        id: "\d+"
teams_games_list:
    path: /teams/{id}/games
    defaults: { _controller: EUMainBundle:Team:listGames }
    methods: [GET]
    requirements:
        id: "\d+"
