<?php

namespace EU\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends EntityRepository
{
    public function getBetsForActivityFeed($limit)
    {
        $qb = $this->createQueryBuilder('b')
                ->orderBy('b.updatedAt', 'DESC')
                ->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }
}
