<?php

namespace EU\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findNextGames($limit)
    {
        $qb = $this->createQueryBuilder('g')
                ->where('g.startTime > :now')
                ->setParameter('now', new \DateTime())
                ->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }
}
