<?php

namespace EU\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PotRepository extends EntityRepository
{
}
